OBJS = ast.cmx parser.cmx scanner.cmx analyzer2.cmx maze.cmx

maze : $(OBJS)
	ocamlfind ocamlopt $(OBJS) -o maze

scanner.ml : scanner.mll
	ocamllex scanner.mll

parser.ml parser.mli : parser.mly 
	ocamlyacc parser.mly 

%.cmo : %.ml
	ocamlc -c $<

%.cmi : %.mli
	ocamlc -c $<

%.cmx : %.ml 
	ocamlfind ocamlopt -c $<

###Generated by "ocamldep *.ml *.mli" after building scanner.ml and parser.ml
ast.cmo :
ast.cmx :
maze.cmo : analyzer2.cmo scanner.cmo parser.cmi ast.cmo
maze.cmx : analyzer2.cmx scanner.cmx parser.cmx ast.cmx
parser.cmo : ast.cmo parser.cmi
parser.cmx : ast.cmx parser.cmi
scanner.cmo : parser.cmi
scanner.cmx : parser.cmx
analyzer2.cmo: ast.cmo
analyzer2.cmx: ast.cmx
parser.cmi : ast.cmo

.PHONY : clean
clean: 
	ocamlbuild -clean
	rm -rf testall.log *.diff maze scanner.ml parser.ml parser.mli
	rm -rf *.cmx *.cmi *.cmo *.o a.out




