OBJS = ast.cmx codegen.cmx parser.cmx scanner.cmx analyzer.cmx maze.cmx 

maze : $(OBJS)
	ocamlfind ocamlopt -linkpkg -package llvm str.cmxa -package llvm.analysis $(OBJS) -o maze 

scanner.ml : scanner.mll
	ocamllex scanner.mll

parser.ml parser.mli : parser.mly 
	ocamlyacc parser.mly 

%.cmo : %.ml
	ocamlc -c $<

%.cmi : %.mli
	ocamlc -c $<

%.cmx : %.ml 
	ocamlfind ocamlopt -c -package llvm str.cmxa $<

###Generated by "ocamldep *.ml *.mli" after building scanner.ml and parser.ml
ast.cmo :
ast.cmx :
codegen.cmo : ast.cmo
codegen.cmx : ast.cmx	
maze.cmo : analyzer.cmo scanner.cmo parser.cmi codegen.cmo ast.cmo
maze.cmx : analyzer.cmx scanner.cmx parser.cmx codegen.cmx ast.cmx
parser.cmo : ast.cmo parser.cmi
parser.cmx : ast.cmx parser.cmi
scanner.cmo : parser.cmi
scanner.cmx : parser.cmx
analyzer.cmo: ast.cmo
analyzer.cmx: ast.cmx
parser.cmi : ast.cmo

.PHONY : clean
clean: 
	ocamlbuild -clean
	rm -rf testall.log *.diff maze scanner.ml parser.ml parser.mli
	rm -rf *.cmx *.cmi *.cmo *.o *.out *.ll




